POST http://localhost:8081/auth/updatePwd
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NSwiZXhwIjoxNzgyODg5ODgwfQ.84xkygvOEXih5G3_u_KTJdIFlhbr80t0pO1kUJfTXBg

oldPassword=123456&newPassword=654321