POST http://localhost:8081/patient/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6MSwiZXhwIjoxNzgyOTI4MDYwfQ.4Fb2mrN90AMt8pyZ2WiBI8ZkS6DMB8W1mXTdryKe5uM

{
  "id":4,
  "name":"张三三",
  "age":59,
  "chronicType":"高血压+高血脂"
}