GET http://localhost:8081/patient/page?pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6NSwiZXhwIjoxNzgyODkyODY5fQ.vNX26u5Hqg8M-f07TJrVcSeNMBWR_fMg5azoWYQPTiw