GET http://localhost:8081/follow/page?patientId=4&pageNum=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6MSwiZXhwIjoxNzgyOTI4MDYwfQ.4Fb2mrN90AMt8pyZ2WiBI8ZkS6DMB8W1mXTdryKe5uM