POST http://localhost:8081/follow/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInVzZXJJZCI6MSwiZXhwIjoxNzgyOTI4MDYwfQ.4Fb2mrN90AMt8pyZ2WiBI8ZkS6DMB8W1mXTdryKe5uM

{
  "patientId":4,
  "followDate": "2026-07-01",
  "bloodPressure": "135/85mmHg",
  "bloodSugar": "6.8mmol/L",
  "medicineRecord": "每日硝苯地平一片",
  "doctorSuggest": "低盐饮食，每周监测三次血压"
}